<?php

/**
 * @file
 *
 * This module provides Elasticsearch index plugin management functionality.
 */

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_delete().
 */
function elasticsearch_helper_index_management_entity_delete(EntityInterface $entity) {
  /** @var \Drupal\elasticsearch_helper_index_management\IndexingStatusOperationManagerInterface $status_manager */
  $status_manager = \Drupal::service('elasticsearch_helper_index_management.index_status_operation_manager');

  // Remove all reference to an entity in indexing status table.
  $status_manager->deleteIndexingStatus($entity);
}
